version: ""

formatter: "markdown"

header-from: "docs/header.md"
footer-from: "docs/footer.md"

sections:
  show:
    - header
    - requirements
    - data-sources
    - providers
    - modules
    - inputs
    - outputs
    - footer

content: |-
  {{  include "docs/template.md"  }}

  {{  .Header  }}

  {{  .Requirements  }}

  {{  .Providers  }}

  {{  .Modules  }}

  {{  .Inputs  }}

  {{  .Outputs  }}

  {{  .Footer  }}

output:
  file: "README.md"
  mode: inject
  template: |-
    <!--  BEGIN_TF_DOCS -->
    {{ .Content }}
    <!--  END_IF_DOCS -->

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: required